[package]
name = "voxel-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
voxel = { path = "../voxel" }

clap = { version = "4.4.8", features = ["derive"] }
log = "0.4.17"
env_logger = "0.10.0"