[workspace]
members = ["voxel", "voxel-game"]
default-members = ["voxel", "voxel-game"]

[workspace.package]
edition = "2"

[profile.release]
# enable debug for profiling
debug = true

[profile.dev]
opt-level = 1
